#!/usr/bin/env node

const moment = require('moment')
const client = require('../server/database')

;(async function getBlocksForLastDay() {

  const before = moment()
    .subtract(Number(4), 'days')
    .toDate()
    .toISOString()

  await client.query(
    `DELETE FROM blocks WHERE timestamp < $1`,
    [before]
  )

  process.exit(0)
})()



