#!/usr/bin/env node

const app = require('../server/app')
const { subscribeToVechainBlocks } = require('../server/lib/connex')
const port = process.env.PORT
const path = require('path')
const childProcess = require('child_process')
const logger = require('../server/lib/logger')

let gettingMissingInProgress = false

app.listen(port, async () => {
  console.log(`server started on port ${port}`)
  await startVechainConnection()
})

async function startVechainConnection() {
  try {
    setInterval(() => {
      if (!gettingMissingInProgress) {
        gettingMissingInProgress = true
        const gettingMissing = childProcess.fork(path.join(__dirname, './getMissingBlocksAndTransactions'))
        gettingMissing.on('exit', function() {
          gettingMissingInProgress = false
        })
      }
    }, 5000)
    await subscribeToVechainBlocks()
  } catch(error) {
    logger.error(`[startVechainConnection]: ${error.message}`)
    setTimeout(async () => {
      await startVechainConnection()
    }, 500)
  }
}
