function addIds(arr) {
  return arr.map((x, i) => ({
    ...x,
    id: Math.floor(Math.random() * 10000)+i,
    contract: 'fake',
  }))
}

// if (data.block.number % 4 === 1) {
//   setTransactionsBlock1(addIds([...TRANSACTIONS_SET_2].slice(0, Math.ceil(TRANSACTIONS_SET_1.length / Math.random()))))
// } else if (data.block.number % 4 === 2) {
//   setTransactionsBlock2(addIds([...TRANSACTIONS_SET_1].slice(0, Math.ceil(TRANSACTIONS_SET_1.length / Math.random()))))
// } else if (data.block.number % 4 === 3) {
//   setTransactionsBlock3(addIds([...TRANSACTIONS_SET_1].slice(0, Math.ceil(TRANSACTIONS_SET_1.length / Math.random()))))
// } else {
//   setTransactionsBlock4(addIds([...TRANSACTIONS_SET_1].slice(0, Math.ceil(TRANSACTIONS_SET_1.length / Math.random()))))
// }

const TRANSACTIONS_SET_1 = [
  { vthoBurn: 36 },
  { vthoBurn: 21 },
  { vthoBurn: 60 },
  { vthoBurn: 36 },
  { vthoBurn: 60 },
  { vthoBurn: 40 },
  { vthoBurn: 60 },
  { vthoBurn: 60 },
  { vthoBurn: 60 },
  { vthoBurn: 60 },
  { vthoBurn: 60 },
  { vthoBurn: 60 },
  { vthoBurn: 60 },
  { vthoBurn: 51 },
  { vthoBurn: 40 },
  { vthoBurn: 60 },
  { vthoBurn: 21 },
  { vthoBurn: 60 },
  { vthoBurn: 40 },
  { vthoBurn: 60 },
  { vthoBurn: 40 },
  { vthoBurn: 60 },
  { vthoBurn: 60 },
  { vthoBurn: 60 },
  { vthoBurn: 60 },
  { vthoBurn: 36 },
  { vthoBurn: 21 },
  { vthoBurn: 60 },
  { vthoBurn: 38 },
  { vthoBurn: 76 },
  { vthoBurn: 51 },
  { vthoBurn: 60 },
  { vthoBurn: 36 },
  { vthoBurn: 21 },
  { vthoBurn: 40 },
  { vthoBurn: 60 },
  { vthoBurn: 40 },
  { vthoBurn: 60 },
  { vthoBurn: 60 },
  { vthoBurn: 40 },
  { vthoBurn: 40 },
  { vthoBurn: 47 },
  { vthoBurn: 21 },
  { vthoBurn: 47 },
  { vthoBurn: 21 },
  { vthoBurn: 21 },
  { vthoBurn: 60 },
  { vthoBurn: 36 },
  { vthoBurn: 60 },
  { vthoBurn: 40 },
  { vthoBurn: 60 },
  { vthoBurn: 40 },
  { vthoBurn: 40 },
  { vthoBurn: 60 },
  { vthoBurn: 40 },
  { vthoBurn: 60 },
  { vthoBurn: 125 },
  { vthoBurn: 60 },
  { vthoBurn: 40 },
  { vthoBurn: 62 },
  { vthoBurn: 62 },
  { vthoBurn: 62 },
  { vthoBurn: 62 },
  { vthoBurn: 426 },
  { vthoBurn: 105 },
  { vthoBurn: 36 },
  { vthoBurn: 21 },
  { vthoBurn: 40 },
  { vthoBurn: 40 },
  { vthoBurn: 60 },
  { vthoBurn: 36 },
  { vthoBurn: 21 },
  { vthoBurn: 60 },
  { vthoBurn: 40 },
  { vthoBurn: 21 },
  { vthoBurn: 21 },
  { vthoBurn: 227 },
  { vthoBurn: 206 },
  { vthoBurn: 60 },
  { vthoBurn: 209 },
  { vthoBurn: 40 },
  { vthoBurn: 60 },
  { vthoBurn: 62 },
  { vthoBurn: 21 },
  { vthoBurn: 605 },
  { vthoBurn: 629 },
  { vthoBurn: 60 },
  { vthoBurn: 606 },
  { vthoBurn: 40 },
  { vthoBurn: 832 },
  { vthoBurn: 60 },
  { vthoBurn: 832 },
  { vthoBurn: 21 },
  { vthoBurn: 40 },
  { vthoBurn: 60 },
  { vthoBurn: 36 },
  { vthoBurn: 60 },
  { vthoBurn: 21 },
  { vthoBurn: 21 },
  { vthoBurn: 36 },
  { vthoBurn: 60 },
  { vthoBurn: 1187 },
  { vthoBurn: 21 },
]

const TRANSACTIONS_SET_2 = [
  { vthoBurn: 40, },
  { vthoBurn: 36, },
  { vthoBurn: 36, },
  { vthoBurn: 40, },
  { vthoBurn: 1100, },
  { vthoBurn: 60, },
  { vthoBurn: 60, },
  { vthoBurn: 23, },
  { vthoBurn: 21, },
  { vthoBurn: 60, },
  { vthoBurn: 23, },
  { vthoBurn: 21, },
  { vthoBurn: 40, },
  { vthoBurn: 168, },
  { vthoBurn: 21, },
  { vthoBurn: 21, },
  { vthoBurn: 40, },
  { vthoBurn: 1300, },
  { vthoBurn: 60, },
  { vthoBurn: 40, },
  { vthoBurn: 60, },
  { vthoBurn: 40, },
  { vthoBurn: 60, },
  { vthoBurn: 60, },
  { vthoBurn: 40, },
  { vthoBurn: 21, },
  { vthoBurn: 96, },
  { vthoBurn: 40, },
  { vthoBurn: 60, },
  { vthoBurn: 36, },
  { vthoBurn: 40, },
  { vthoBurn: 40, },
  { vthoBurn: 60, },
  { vthoBurn: 60, },
  { vthoBurn: 40, },
  { vthoBurn: 1600, },
]

module.exports = {
  TRANSACTIONS_SET_1,
  TRANSACTIONS_SET_2,
}
